services:
  inbox:
    container_name: inbox
    build: inbox
    ports:
      - "25:25"
    env_file: ".env"
    volumes:
      - ./certs/inbox:/certs/inbox:ro
      - vhosts:/var/mail/vhosts/

  outbox:
    container_name: outbox
    build: outbox
    ports:
      - "465:465"
    env_file: ".env"
    volumes:
      - ./certs/outbox:/certs/outbox:ro
      - vhosts:/var/mail/vhosts/
    networks:
      - mailnet

  redis:
    image: redis:latest
    container_name: redis_mail
    volumes:
      - redis_data:/data
    networks:
      mailnet:
        ipv4_address: 172.18.0.3

  dovecot:
    image: dovecot/dovecot:latest
    container_name: dovecot
    volumes:
      - ./conf/dovecot:/etc/dovecot/conf.d
      - vhosts:/var/mail/vhosts/
      - ./certs/dovecot:/certs/dovecot:ro
    environment:
      - DOVECOT_USERDB_ARGS=driver=redis
      - DOVECOT_PASSWORDDB_ARGS=driver=redis
    depends_on:
      - redis
    networks:
      - mailnet
    ports:
      - "993:993"

volumes:
  redis_data:
  vhosts:

networks:
  mailnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
