services:
  inbox:
    container_name: inbox
    image: carlgo11/mailroom-inbox
    pull_policy: always
    ports:
      - "25:25"
    volumes:
      - ./certs/inbox:/certs/inbox:ro
      - ./certs/clients/users:/certs/clients/users:ro
      - vhosts:/var/mail/vhosts
      - /var/log/inbox.log:/tmp/inbox.log
    env_file: .env
    entrypoint: sh -c "node src/index.js 2>&1 | tee /tmp/inbox.log"
    depends_on:
      - redis
    networks:
      default:
        aliases:
          - inbox
      postnet:
        ipv4_address: 172.22.0.4
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
    security_opt:
      - apparmor=inbox-profile

  outbox:
    container_name: outbox
    image: carlgo11/mailroom-outbox
    ports:
      - "465:465"
    volumes:
      - ./certs/outbox:/certs/outbox:ro
      - ./certs/clients:/certs/clients:ro
      - ./certs/dkim:/certs/dkim:ro
      - vhosts:/var/mail/vhosts
    env_file: .env
    depends_on:
      - redis
    read_only: true
    tmpfs:
      - /tmp
    networks:
      postnet:
        ipv4_address: 172.22.0.5

  redis:
    image: redis:alpine
    container_name: redis_mail
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      postnet:
        ipv4_address: 172.22.0.3

  dovecot:
    container_name: dovecot
    image: dovecot/dovecot:latest
    ports:
      - "993:993"
    volumes:
      - ./conf/dovecot:/etc/dovecot/conf.d:ro
      - ./certs/dovecot:/certs/dovecot:ro
      - ./certs/clients:/certs/clients:ro
      - vhosts:/var/mail/vhosts
    env_file: .env
    depends_on:
      - redis
    networks:
      postnet:
        ipv4_address: 172.22.0.6
    read_only: true
    tmpfs:
      - /run/dovecot
      - /var/lib/dovecot
      - /tmp

  rspamd:
    container_name: rspamd
    image: carlgo11/mailroom-rspamd
    ports:
      - "11334:11334"
    volumes:
      - rspamd_confdir:/etc/rspamd
      - rspamd_dbdir:/var/lib/rspamd
    env_file: .env
    environment:
      - RSPAMD_REDIS_SERVERS=rspamd-compose-redis
    depends_on:
      - redis
    networks:
      postnet:
        ipv4_address: 172.22.0.7

  controller:
    container_name: controller
    build: ./controller
    ports:
      - "127.0.0.1:6804:6804/tcp"
    volumes:
      - ./certs:/certs
    env_file: .env
    networks:
      - postnet

  unbound:
    container_name: unbound
    image: mvance/unbound
    restart: unless-stopped
    networks:
      postnet:
        ipv4_address: 172.22.0.8

volumes:
  redis_data:
  vhosts:
  rspamd_dbdir:
  rspamd_confdir:

networks:
  postnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/28
