services:
  inbox:
    container_name: inbox
    build: inbox
    ports:
      - "25:25"
    volumes:
      - ./certs/inbox:/certs/inbox:ro
      - vhosts:/var/mail/vhosts/
      - ./certs/clients/users:/certs/clients/users:ro
      - ./inbox/src:/usr/src/inbox/src
      - ./inbox/test:/usr/src/inbox/test
    env_file: ".env"
    depends_on:
      - redis
    networks:
      - postnet
    read_only: true
    tmpfs:
      - /tmp

  outbox:
    container_name: outbox
    build: outbox
    ports:
      - "465:465"
    volumes:
      - ./certs/outbox:/certs/outbox:ro
      - ./certs/clients:/certs/clients
      - ./certs/dkim:/certs/dkim:ro
      - vhosts:/var/mail/vhosts/
      - ./outbox/src/:/usr/src/outbox/src
      - ./outbox/test/:/usr/src/outbox/test
    env_file: ".env"
    depends_on:
      - redis
    networks:
      - postnet
    read_only: true
    tmpfs:
      - /tmp

  redis:
    container_name: redis_mail
    image: redis:alpine
    ports:
      - "6379:6379/tcp"
    volumes:
      - redis_data:/data
    networks:
      postnet:
        ipv4_address: 172.18.0.3

  dovecot:
    container_name: dovecot
    image: dovecot/dovecot:latest
    ports:
      - "993:993"
    volumes:
      - ./conf/dovecot:/etc/dovecot/conf.d
      - vhosts:/var/mail/vhosts/
      - ./certs/dovecot:/certs/dovecot:ro
      - ./certs/clients:/certs/clients:ro
    env_file: .env
    depends_on:
      - redis
    networks:
      - postnet
    read_only: true
    tmpfs:
      - /run/dovecot
      - /var/lib/dovecot
      - /tmp

  rspamd:
    container_name: rspamd
    build: rspamd
    ports:
      - "11334:11334"
    volumes:
      - rspamd_confdir:/etc/rspamd
      - rspamd_dbdir:/var/lib/rspamd
    env_file: .env
    environment:
      - RSPAMD_REDIS_SERVERS=rspamd-compose-redis
    depends_on:
      - redis
    networks:
      - postnet

  controller:
    container_name: controller
    build: controller
    ports:
      - "6804:6804"
    volumes:
      - ./certs:/certs
    env_file: .env
    networks:
      - postnet

volumes:
  redis_data:
  vhosts:
  rspamd_dbdir:
  rspamd_confdir:

networks:
  postnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
