services:
  inbox:
    container_name: inbox
    build: inbox
    ports:
      - "25:25"
    env_file: ".env"
    volumes:
      - ./certs/inbox:/certs/inbox:ro
      - vhosts:/var/mail/vhosts/
    read_only: true
    tmpfs:
      - /tmp
    depends_on:
      - redis
      - rspamd
    networks:
      - postnet

  outbox:
    container_name: outbox
    build: outbox
    ports:
      - "465:465"
    env_file: ".env"
    volumes:
      - ./certs/outbox:/certs/outbox:ro
      - vhosts:/var/mail/vhosts/
    read_only: true
    tmpfs:
      - /tmp
    depends_on:
      - redis
    networks:
      - postnet

  redis:
    image: redis:latest
    container_name: redis_mail
    volumes:
      - redis_data:/data
    networks:
      postnet:
        ipv4_address: 172.18.0.3

  dovecot:
    image: dovecot/dovecot:latest
    container_name: dovecot
    read_only: true
    tmpfs:
      - /run/dovecot
      - /var/lib/dovecot
      - /tmp
    volumes:
      - ./conf/dovecot:/etc/dovecot/conf.d
      - vhosts:/var/mail/vhosts/
      - ./certs/dovecot:/certs/dovecot:ro
    depends_on:
      - redis
    networks:
      - postnet
    ports:
      - "993:993"

  rspamd:
    build: rspamd
    container_name: rspamd
    volumes:
      - rspamd_confdir:/etc/rspamd
      - rspamd_dbdir:/var/lib/rspamd
    ports:
      - "11333:11333"
      - "11334:11334"
    networks:
      - postnet
    depends_on:
      - redis
    environment:
      - RSPAMD_REDIS_SERVERS=rspamd-compose-redis
    env_file: ".env"

volumes:
  redis_data:
  vhosts:
  rspamd_dbdir:
  rspamd_confdir:

networks:
  postnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
