name: Publish Development Images

on: [ push ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ GITHUB.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push inbox image
        uses: docker/build-push-action@v6
        with:
          context: inbox
          platforms: linux/amd64,linux/arm/v6,linux/arm64,linux/s390x
          push: true
          tags: |
            carlgo11/mailroom-inbox:dev
            ghcr.io/carlgo11/mailroom-inbox:dev

      - name: Build and Push outbox image
        uses: docker/build-push-action@v6
        with:
          context: outbox
          platforms: linux/amd64,linux/arm/v6,linux/arm64,linux/s390x
          push: true
          tags: |
            carlgo11/mailroom-outbox:dev
            ghcr.io/carlgo11/mailroom-outbox:dev
