name: Publish Inbox image

on:
  push:
    paths:
      - inbox/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout smtp-server dependency
        uses: actions/checkout@v4
        with:
          repository: 'carlgo11/smtp-server'
          ref: 'master'
          path: 'inbox/smtp-server'

      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push inbox image
        uses: docker/build-push-action@v6
        with:
          context: inbox
          file: inbox/Dockerfile.dev
          #          platforms: linux/amd64,linux/arm/v6,linux/arm64,
          push: true
          tags: carlgo11/mailroom-inbox:dev
